### PR TITLE
 Add support for Firewatch base config

### PR DESCRIPTION
**Pull request by oharan2**
For occurring steps and workflows in our project, we want to initialize a source that holds our Firewatch base config.

Once set up (optional), our Openshift-ci env `FIREWATCH_CONFIG` values will be added on top of that.

This PR allows the user to override the base config by:
-  replacing steps with general patterns with specific step names and vice versa
-  updating existing rules with new logic. 

For example: 
The team consistently uses the rule `{"step": "failure", "ignore": "True"...}` and holds it in their base config file; a specific scenario might need to override it and set the "ignore" to "False".
in this case, the scenario will mention this step in their `FIREWATCH_CONFIG` env var.

Unit-tests main additions:
- steps containing patterns and steps that matches them are co-existing when configured on the same config data
- config data collected from both base config and additional logic from env var is functioning well

### CODE REVIEW

**Comment by redhat-qe-bot1** [comment]
Report bugs in [Issues](https://github.com/myakove/github-webhook-server/issues)

The following are automatically added:
 * Add reviewers from OWNER file (in the root of the repository) under reviewers section.
 * Set PR size label.
 * New issue is created for the PR. (Closed when PR is merged/closed)
 * Run [pre-commit](https://pre-commit.ci/) if `.pre-commit-config.yaml` exists in the repo.

Available user actions:
 * To mark PR as WIP comment `/wip` to the PR, To remove it from the PR comment `/wip cancel` to the PR.
 * To block merging of PR comment `/hold`, To un-block merging of PR comment `/hold cancel`.
 * To mark PR as verified comment `/verified` to the PR, to un-verify comment `/verified cancel` to the PR.
        verified label removed on each new commit push.
 * To cherry pick a merged PR comment `/cherry-pick <target branch to cherry-pick to>` in the PR.
    * Multiple target branches can be cherry-picked, separated by spaces. (`/cherry-pick branch1 branch2`)
    * Cherry-pick will be started when PR is merged
 * To build and push container image command `/build-and-push-container` in the PR (tag will be the PR number).
 * To add a label by comment use `/<label name>`, to remove, use `/<label name> cancel`
 * To assign reviewers based on OWNERS file use `/assign-reviewers`
 * To check if PR can be merged use `/check-can-merge`

<details>
<summary>Supported /retest check runs</summary>

 * This repository does not support retest actions
</details>

<details>
<summary>Supported labels</summary>

 * hold
 * verified
 * wip
 * lgtm

</details>

**Comment by oharan2** [comment]
Pending the merge of #193

**Review by calebevans — APPROVED** [review]
/lgtm

**Pull request merged**
