### PR TITLE
Set interop users as approvers

### PR DESCRIPTION
**Pull request by calebevans**

### CODE REVIEW

**Comment by msi-b1** [comment]
macharya0907 can not be added as reviewer. 422 {"message": "Reviews may only be requested from collaborators. One or more of the users or teams you specified is not a collaborator of the RedHatQE/firewatch repository.", "documentation_url": "https://docs.github.com/rest/pulls/review-requests#request-reviewers-for-a-pull-request", "status": "422"}

**Comment by msi-b1** [comment]
macharya0907 can not be added as reviewer. 422 {"message": "Reviews may only be requested from collaborators. One or more of the users or teams you specified is not a collaborator of the RedHatQE/firewatch repository.", "documentation_url": "https://docs.github.com/rest/pulls/review-requests#request-reviewers-for-a-pull-request", "status": "422"}

**Review by dfrazzette — APPROVED** [review]

**Pull request merged**
